version: '3.1'
services:
  webapp:
    build: ./app
    ports:
      - ${WEBAPP_PORT}:${WEBAPP_PORT}
    env_file:
      - ./.env
    environment:
      - APPLICATION_HOST=srv
      - PORT=${WEBAPP_PORT}
  srv:
    build: ./services/cmd/srv
    ports:
      - ${APPLICATION_PORT}:${APPLICATION_PORT}
    env_file:
      - ./.env
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
  db:
    image: postgres
    restart: always
    env_file:
      - ./.env
  adminer:
    image: adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:8080