version: '3.1'
services:
  db:
    image: postgres
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    env_file:
      - ./.env
  testdb:
    image: postgres
    restart: always
    ports:
      - ${POSTGRES_DBTEST_PORT}:5432
    env_file:
      - ./.env
  integrationdb:
    image: postgres
    restart: always
    ports:
      - ${POSTGRES_INTEGRATION_PORT}:5432
    env_file:
      - ./.env
  adminer:
    image: adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:8080